version: '3.8'
services:
  backend:
    build: ./Back-end
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    volumes:
      - ./database:/app/database  # Mount the database folder inside the backend container

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
