name: Deploy Static Site with Docker

on:
  push:
    branches:
      - main  # Exécute l’action à chaque push sur la branche `main`
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🐳 Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🔨 Construire et pousser l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/challengehub:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/challengehub:latest

      - name: 🚀 Déployer sur un serveur (exemple avec SSH)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/challengehub:latest
            docker stop challengehub || true
            docker rm challengehub || true
            docker run -d -p 80:80 --name challengehub ${{ secrets.DOCKER_USERNAME }}/challengehub:latest
